### PR TITLE
possible missing link in 'Relation of Process Document to Patent Policy' section

### PR DESCRIPTION
**Pull request by himorin**
only closing link exists.

### CODE REVIEW

**Comment by dwsinger** [comment]
Hi.

thanks, but if you look at the published document I think you'll find that there is a hyperlink there; it's made by Bikeshed processing the [[! ]] into a bibliography entry and hyperlink.

**Comment by himorin** [comment]
In one line before (from this line), there is both a link and bikeshed [[! ]] to a bibliography entry for Membership Agreement. And I thought isolated closing `</a>` were inserted to put similar markup for patent policy.

Which is better: to keep, or to remove `</a>`?

**Comment by dwsinger** [comment]
weird.  I'll let the editor sort me out

**Comment by frivoal** [comment]
I suspect the link on Membership Agreement is an accidental leftover from before the document was edited in Bikeshed. We should probably remove it, as well as the stray closing `</a>` tag after "The W3C Patent Policy".
That said, having a direct link as well isn't wrong either, so we could go either way. If anyone has a strong opinion, please state it, otherwise, I'll figure out what my favorite way to clean this up is and do it in a little while.

**Pull request merged**
