### PR TITLE
remove member

### PR DESCRIPTION
**Pull request by nrooney**
remove member from "member organisation" for tag and AB rep restrictions #163

### CODE REVIEW

**Comment by dwsinger** [comment]
LGTM

**Comment by chaals** [comment]
I think this needs to be considered alongside who nominated someone and the rest of #176 

Example 1:
Jo works for W3C member Ace Accessibility, but is on the board of Accessibility Braves which certifies accessibility bug hunters and is not a W3C member.
Charlie works for W3C member Cool Access, and is on the board of Accessibility Braves.

If each is nominated by their employer, can Charlie and Jo both be on the TAG?

Can they both be nominated by Cool Access, at successive elections?

Does it matter whether Accessibility Braves is formally incorporated (i.e. a legal entity, or "juridical person") or not (e.g. like W3C)?

Example 2:
Jo works for Ace Accessibility, but as Accessibility Braves became a member, Jo is their AC rep.
Yuan is Ace Accessibility's AC rep.

Can Jo and Yuan each nominate themselves to the AB?

Example 3:
Charlie's employer Cool Access subcontracts Biddable Worx, a W3C member, to represent them in W3C working groups.
Jan works for Biddable Worx, and is working on that subcontract.

Can Charlie and Jan both be on the TAG?
Does it make a difference whether the contract represents 0.8% or 80% of Biddable Worx' income?

**Comment by dwsinger** [comment]
Perhaps we can state that a change of affiliation is either (a) a change of employment or (b) the originally nominating member organization withdraws their support, i.e. would not re-nominate now?

Other conflicts, affiliations, interests, I think can be the part of reasonable disclosure.

**Comment by cwilso** [comment]
That last statement seems more appropriate to #176 .

**Comment by frivoal** [comment]
Not objecting, but I am not sure I see the need for the removal of "Member" here. If an individual is part of an organization that's not a member, then presumably they are an invited expert and represent themselves, rather than that organization. So organizations which are not members cannot have anyone on the TAG or the AB, so limiting them to at most 1 does nothing since they can only have 0 anyway.

**Comment by chaals** [comment]
It is fairly straightforward for two member organisations to nominate people who happen to work for the same non-member organisation. It seems anomalous to allow such a case to provide a non-member with a position that we explicitly deny to members.

**Comment by frivoal** [comment]
I guess so. My working assumption was that the non-member company would be unrelated to W3C, and that the restriction was therefore not particularly useful. But maybe this assumption is not justified. Anyway, even if I am not 100% sure it is useful, I don't see the harm, and it is fewer words in the end.

**Pull request merged**
