### PR TITLE
Avoid implying that elected members of the AB/TAG represent an organisation

### PR DESCRIPTION
**Pull request by frivoal**
Phrasing improvement suggested by @swickr in https://github.com/w3c/w3process/issues/208#issuecomment-438494615

### CODE REVIEW

**Comment by swickr** [comment]
s/thisis/this is/

**Comment by dwsinger** [comment]
this leaves "the organization must have returned to having at most one seat." but I think the sense is nonetheless clear. OK by me.

**Comment by frivoal** [comment]
> OK by me.

I read that as a personal +1. If you meant it as a chair's declaration of it being good to merge, I'd appreciate an explicit statement to that effect.

**Comment by frivoal** [comment]
The [CfC about the 2019 process](https://lists.w3.org/Archives/Public/public-w3process/2018Nov/0001.html) is closed and the chair has concluded we do have consensus. Merging.

**Pull request merged**
