### PR TITLE
Add text on vacating TAG and AB seats

### PR DESCRIPTION
**Pull request by nrooney**
Added some text to help clarify. #175

### CODE REVIEW

**Comment by dwsinger** [comment]
Don't think so; I think we recently changed that the TAG seat is NOT vacated immediately when affiliation change causes duplicate membership, but must be resolved at the next election.

**Comment by chaals** [comment]
@dwsinger not sure which bit you are referring to. The participation constraints explicitly have different rules for AB compared to TAG, to enable the case you outline.

In any event, I don't see anything in the pull request that changes that particular case.

**Comment by dwsinger** [comment]
My read of the PR is that it says
<p>An Advisory Board or TAG participant's seat is vacated immediately when one of the following applies:</p>
…
<li>an Advisory Board or TAG participant changes affiliations such that the
            <a href="#AB-TAG-constraints">Advisory Board and TAG participation constraints</a>
            are no longer met, or</li>


which is not true for the TAG; the seat is NOT vacated immediately; the participation constraints have to be satisfied by the end of the next regularly scheduled election.

What am I missing?

**Comment by frivoal** [comment]
I think another relevant bit worth clarifying is what "change of affiliation" means. Some cases are easy, some are not:

Easy case:
1. A person used to be an employee / director of a member company, now is an employee / director of a different member company

Various less obvious cases:

2. A person used to be self-employed, has now incorporated.
3. A person used to be an IE, now (without change of employment or incorporation), has become a paying member…
    1. … because they just joined as an individual
    2. … because the company they own/control just joined
    3. … because the company that employs them just joined
4. 2 + 3.ii at the same time
5. A person used to be an employee / director of a member company, now is a contractor of the same member company
6. A person used to be a contractor for several member companies, now is an employee / director of one of them
   1. part time, and retains their previous contracting clients
   2. full time, and no longer works for their previous contracting clients.
7. A person used to be an employee or contractor of a member company, now no longer receives any financial compensation from that member company, but the company is still willing to let the person participate in their name
8. A person who used to be employee / director in one member company continues to be, but now is additionally director / employee in one additional company…
   1. … which is a member company
   2. … which is a not member company
9. A Invited Expert used to be self employed, and now is the employee of an company which is not a member
10. A Invited Expert used to be and employee / director of a company which is not a member, and now is the employee / director of an other company which is also not a member

(Plus, any of the above in the opposite direction.)

While I don't think all of the above have necessarily happened to AB/TAG members yet, I can think of concrete examples of individuals active in W3C for pretty much all of the above (hell, I've probably been through half of these myself…)

The above laundry list is certainly not something we should incorporate into the process directly, but some high level principle by which we could judge which case falls on which side would be welcome.

----
My take is that:

2, 3.i, 3.ii, 4, 5, 7, 8.ii, 9, 10 don't seem useful to me to classify as changes in affiliation

3.iii, 6.ii are probably worth counting as changes in affiliation

6.i, 8.i I don't know.

----
I think the underlying principle behind that classification is that, as far as their w3c activity is concerned, if a person switches between being someone's agent to someone else's agent, or from being someone's agent to representing themselves, it is a change of affiliation, and otherwise, it is not, and that you can only be someone's agent in w3c if that someone is a member (otherwise you're representing yourself).

**Comment by frivoal** [comment]
Just realized that my previous comment was more appropriate for a different issue. Deleting and reposing there: #176

**Comment by dwsinger** [comment]
not ok, the TAG affiliation change is resolved at the next election, not immediately, see 2.5.1...

**Comment by nrooney** [comment]
not true for the TAG point - please rewrite.

**Comment by dwsinger** [comment]
much clearer (i think)

**Comment by frivoal** [comment]
> much clearer (i think)

What is? I don't see any update since issues were raised against the initial text.

**Comment by dwsinger** [comment]
still has problems, close without applying?

**Comment by dwsinger** [comment]
@frivoal My mistake. I am concerned we seem more likely to introduce problems here than solve them

**Comment by dwsinger** [comment]
Indeed, this pull Request now appears to say that AB members resolve participation constraints at the next election, like TAG; they don't, AB has to resolve it immediately. Do we really need to make this edit?

**Comment by frivoal** [comment]
I believe that on the last call, we agreed to close this as wontfix. Didn't we?

**Comment by dwsinger** [comment]
I think so.

**Pull request closed without merging**
