### PR TITLE
clarify withdrawing a Rec

### LINKED ISSUE #138: Editorial improvements to obsolete/superceded
From Andreas in AC review:

#### Change
* Section 6.9
* Description: A Recommendation can be declared superseded as well as obsolete.

### Comment
The process is not clear enough. Example:

> W3C may obsolete a Recommendation, for example if the W3C Community decides that the Recommendation no longer represents best practices,

Who is the W3C Community?

In general, the requirements to start a process that obsoletes (rescinds or supersedes) a recommendation are not defined well enough.

> [dwsinger] Hm, we define four very specific cases. What is missing?

It may be just a clarification that this is the only way to start the process. You first define the option that W3C may obsolete a Recommendation. Then you describe the process by starting with "The director may recommend ....". It is not clear from the reading that the described steps are the only, exclusive process  steps to come to an obsolete Recommendation. So it may just need an editorial edit to clarify this.

### PR DESCRIPTION
**Pull request by chaals**
Fix #138 and #141 

Where should proposals be sent? AC mailing list?

### CODE REVIEW

**Comment by chaals** [comment]
If this is the right direction, need to determine how proposals are made to "W3C" before merging.

**Comment by dwsinger** [comment]
Looks plausible but not in the list of 2018 minor post-ballot cleanups

**Comment by dwsinger** [comment]
do we need to re-examine this? it fixes some editorials so I would kinda like to leave it to the editor...

**Comment by dwsinger** [comment]
Over to Natasha to handle, integrate as appropriate (or reject, or reword, etc. as she sees fit)

**Comment by nrooney** [comment]
I actually like the text as it is - short and to the point. The AC can receive an email to the official AC list - that should be sufficient. @chaals if you add this I think we're ok to go.

**Comment by dwsinger** [comment]
yes, I think this cleanup can happen with notification to the AC list. not sure Chaals' input is needed

**Comment by nrooney** [comment]
note to self: review - check if editorial, and bring it in if it is, and if not bring back to CG

**Comment by nrooney** [comment]
On further review, this PR is not ready, please review, edit and re submit

**Comment by jeffjaffe** [comment]
Why in old line 2515 are we taking the Director out of the loop?  Tantek points out in new line 2515 there is an @@/HOWWHERE.

**Pull request closed without merging**
