### PR TITLE
Alternate AC Rep

### PR DESCRIPTION
**Pull request by wseltzer**
Address issue #505 Based on [text proposal](https://github.com/w3c/w3process/issues/505#issuecomment-797266570) from @fantasai

(Additional parenthetical mine; may be unecessary detail.)

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/w3process/pull/524.html" title="Last updated on Apr 30, 2021, 1:53 PM UTC (a49f6df)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/w3process/524/ea8220a...a49f6df.html" title="Last updated on Apr 30, 2021, 1:53 PM UTC (a49f6df)">Diff</a>

### CODE REVIEW

**Review by tantek — CHANGES_REQUESTED** [review]
This is a good start (including the parenthetical), however IMO this is insufficient to capture the needs of this issue. The "may delegate" implies an ephemeral act, and the "any of their rights" etc. implies the need for specific enumeration. Neither of these is desirable.

The need here is to designate an explicitly ongoing alternate, that persists in parallel with the "primary" AC rep, as in all the same abilities to be on the same lists, receive all the same notifications, answer all the same forms etc. with the presumption that any "conflict" between primary & alternate would be up to the primary to resolve (not W3C or any systems thereof) if necessary by un-designating the alternate. The key here is for the alternate to be fully empowered to receive all comms and act as the AC rep, so that if the primary is incapacitated or otherwise unavailable for any reason (unexpected or planned like a vacation), the member's AC participation is expected to continue without interruption.

**Comment by dwsinger** [comment]
I think this is probably ok as the formal process text. However, I am mighty curious to know the details, and that might inform us whether any other process text is needed.

**Comment by wseltzer** [comment]
@tantek, that's the idea for implementation -- the designation sticks until changed, and includes all rights without enumeration.  What do you think needs to be added or changed in Process text?

**Comment by dwsinger** [comment]
Agenda+ to decide if it lands in P2021

**Comment by wseltzer** [comment]
Proposed implementation: 
An organization's AC Rep may designate an Alternate AC Rep, which designation persists until the AC Rep changes or revokes it. Any other action the AC Rep is entitled to take (e.g. responding to AC reviews, voting in elections, joining a group, approving participation requests) may be completed by the AC Rep or Alternate, and binds the organization to the same extent as if the AC Rep had acted. In the event of multiple responses to a request for organizational input, the last response before deadline controls. (Ideally, a shared dashboard helps them coordinate.)

Alternates receive the same email notifications and list subscriptions as AC Reps, and may attend meetings and calls. All participants are asked to ensure that people know "with which hat" they are speaking when commenting, and to avoid overwhelming message frequency.

Questions on the implementation: 
* Should the number of alternates be a maximum of 1? 
* Should alternates and AC Reps both be able to speak on ac-forum, or only one in a given timeframe?
* Should team communicate by default with both AC Rep and Alternate when reaching out to a member?

**Comment by dwsinger** [comment]
General discussion is in #505 thanks

**Comment by tagawa** [comment]
Just to clarify, would designating an alternate AC rep mean both people could perform AC duties simulatenously, or would the original AC rep lose that ability until the alternate designation is revoked? In other words, would they work as a team or pass the baton?

**Comment by wseltzer** [comment]
@tagawa see the proposed implementation in the issue discussion  #505

**Pull request merged**
