### PR TITLE
define "transition request" 

### PR DESCRIPTION
**Pull request by nrooney**
to solve #160

### CODE REVIEW

**Comment by frivoal** [comment]
LGTM, although I would think in addition to this, we should convert the whole spec to bikshed and make use of its cross referencing facilities.

**Comment by jeffjaffe** [comment]
The revision takes the word "advance" out of the sentence.  Does that mean it is a transition request even if the WG goes to a lesser level of maturity?

**Comment by frivoal** [comment]
> The revision takes the word "advance" out of the sentence.

That does not seem intentional or desirable. Let's restore it.

**Comment by dwsinger** [comment]
we need to keep 'advance'...

**Comment by frivoal** [comment]
Restored the word advance. I think we're good to (squash and) merge.

This is editorial, so I don't think we need to discuss on the call, and it is OK to merge as soon as there's an approving review.

**Pull request merged**
