### PR TITLE
spelling fix: judgment

### PR DESCRIPTION
**Pull request by wseltzer**

### CODE REVIEW

**Comment by dwsinger** [comment]
see <https://www.dailywritingtips.com/judgement-or-judgment> ;-)

**Comment by wseltzer** [comment]
we should be consistent. elsewhere and previously, it's judgment.

**Comment by fantasai** [comment]
Can I propose the alternative of fixing the existing occurence to 'judgement' instead? :)

**Comment by nigelmegitt** [comment]
Can I propose sidestepping this and changing it to "assessment" instead? 🙂

**Comment by dwsinger** [comment]
I'm going for "ordered, adjudged and decreed"

<https://en.wikipedia.org/wiki/Legal_doublet>

**Comment by dwsinger** [comment]
2.5 has an existing spelling of "judgment". By the powers invested in me, I decree that we shall be consistent and change 3.5 and 6.2.4.1 to the same. This year.

**Pull request merged**
