### PR TITLE
Only substantive changes do require Director's approval for CR

### PR DESCRIPTION
**Pull request by plehegar**
One minor fix for the document in the changes section, otherwise it is misleading.

### CODE REVIEW

**Comment by dwsinger** [comment]
Hm, are you sure we don't need Director's assent that proposed changes are not substantive (and hence would need wider review)? Just asking, but is the mental model "any change -> get the Director's OK; substantive change -> get the AC and community OK"?

**Comment by plehegar** [comment]
Section 6.4.1 only talks about substantive changes as far as I can tell so the change log is misleading imho and isn't an actual change from Process 2017 to Process 2018. We do allow Groups to publish new CR with only editorial changes without Director's approval:
 https://www.w3.org/Guide/transitions?profile=CR&cr=editorial
(compare that with https://www.w3.org/Guide/transitions?profile=CR&cr=substantive )
If the Group misjudged the change, the Director will notice it before the approval to Proposed Recommendation (the diff with the document previously approved by the Director will highlight the change) and would force the Group to republish a CR instead (and trigger a call for exclusions).

**Comment by swickr** [comment]
The 2017->2018 changes to 6.4.1 do not appear to read on whether _all_ changes to a CR require Director's review or only substantive changes.   Appendix 14 is not the appropriate place to put a clarification of that point.

As I read it, the _MUST_ in 6.4.1 continues to apply to "substantive changes" earlier in the sentence.

**Comment by plehegar** [comment]
@dwsinger should I revise this PR to simply remove the mention of section 6.4.1 in the change log?

**Comment by dwsinger** [comment]
I am remarkably relaxed about what change logs say since they are only informative (and almost no-one reads them, except to find out when something happened)

**Comment by plehegar** [comment]
ok. removing mention of 6.4.1 in the changelog then.

**Pull request merged**
