### PR TITLE
singular

### PR DESCRIPTION
**Pull request by koalie**

### CODE REVIEW

**Comment by dwsinger** [comment]
I think it's old, and fine as a plural.

**Comment by wseltzer** [comment]
editorial; indifferent.

**Comment by dwsinger** [comment]
to sound right, I think it has to change to something like

>Rejection of a Submission Request, and Appeal of a Submission Rejection

(or stay as it is)

**Comment by frivoal** [comment]
Minutes on this topic form the July 15 meeting are here: https://www.w3.org/2020/07/15-w3process-minutes.html#t15

Notably:
> Resolution: Defer to editor

----

This is purely editorial, there isn't 100% agreement about what phrasing is best, so this could go any direction without major issue.

That said, this is a section title, and cross references from other documents sometimes use the section title (rather than its number) to be specific about what they're referring to, so stability has some value.

As the resolution makes this my call, I chose to close it with no action.

@koalie, I hope you can live with this, but if not, you're of course free to reopen.

**Comment by koalie** [comment]
Oh yeah, I can live with it :)

**Pull request closed without merging**
