### PR TITLE
Proposed addition of public channel for AC review

### PR DESCRIPTION
**Pull request by wseltzer**
https://github.com/w3c/w3process/issues/38
supported by discussion in Strategy team

### CODE REVIEW

**Comment by koalie** [comment]
Hi all,

I was just going to open that very issue, and #38.

In practice we have been doing this since December 2014. I was going to suggest section 7.1.1 be updated to reflect practice.
See the [December 2014 announcement](https://lists.w3.org/Archives/Member/w3c-ac-members/2014OctDec/0046.html) in the W3C Member list.

Quoting the relevant part (and linking to the public list's mail archive):
> Starting with the next review form that we publish, you will find the following options for sharing your review comments in the first drop-down menu of the review form:
>
> - Member-visible
> - Member-visible and send email to w3c-ac-forum
> - Public and send email to both w3c-ac-forum and [public-new-work](https://lists.w3.org/Archives/Public/public-new-work/)
> - Team-only

**Comment by frivoal** [comment]
AC reviews are AC rep's opinions. They can make their own opinion public no matter what we say. Also we also already give them the opportunity to post their review to a public channel if they so desire, with the current implementation of the system.

I really don't see what is objectionable in this PR, and I think we should merge it.

@chaals , as you were pushing back, can you explain why it's a problem to you?

**Comment by frivoal** [comment]
Agenda+ to unblock. Either we merge or we go into what's wrong with this

**Comment by chaals** [comment]
Where review comments are made at different levels of confidentiality, it tends to stifle rather than encourage open discussion.

It is more or less always possible to publish one side of an otherwise confidential debate - indeed we added to the process some obligations on W3C to do so in the case of formal objections to a Director's decision.

But there is a real risk that instead of bringing the discussion into the open, putting some review in public will push people who disagree further into the shadows. If they don't feel comfortable in public view, people have often in practice responded to a public argument by making their counter-argument **less** visible than AC-wide.

This is a tension that we address repeatedly. This proposal seems to be optimising for **making some/most content public** over **transparency of a discussion to those who are formally parties to it**, and that seems to me a poor choice.

(Reasonable people have been recorded disagreeing about the right way to do this over centuries. So "your mileage may vary")

**Comment by frivoal** [comment]
@chaals do you think this tension would be addressed if the system that enables people to make their comments public only lets them do so by also making them in member private space, so that they can be responded to without further friction by people who wish to remain in confidence?

**Comment by frivoal** [comment]
This repository has been switched to using bikeshed. Pull request now need to be done against the master branch (instead of the gh-pages branch), against index.bs (instead of index.html).
This pull request predates that. Rebasing.

**Comment by frivoal** [comment]
As per https://www.w3.org/2020/01/29-w3process-minutes.html and https://www.w3.org/2020/02/12-w3process-minutes.html, this issue is deferred to a subsequent cycle of the Process.

**Comment by wseltzer** [comment]
Propose to close as no longer of interest to anyone but the requester.

**Comment by dwsinger** [comment]
closing as suggested

**Comment by frivoal** [comment]
If we're closing this (which I'm OK with), we should probably close #63 and #38 as well, as they're the same question.

**Pull request closed without merging**
