### PR TITLE
Add diagram to 6.9

### PR DESCRIPTION
**Pull request by chaals**
Illustrate the possible ways a Recommendation can be retired...

### CODE REVIEW

**Comment by chaals** [comment]
Waiting on an accessibility check...

**Comment by nrooney** [comment]
is the accessibility check done?

**Comment by LJWatson** [comment]
I recall @Chaals asking about this before it became a PR, but don't recall the outcome. If it helps, feel free to merge the PR, and I'll take a look at the SVG in situ (and make any changes if they seem to be needed).

**Comment by chaals** [comment]
I don't think it is done. As @LJWatson says you can go ahead and merge it anyway, since whatever changes under the hood for accessibility is extremely unlikely to change what the picture looks like.

**Comment by nrooney** [comment]
Thanks both!

**Pull request merged**
