### PR TITLE
editorial clarification

### PR DESCRIPTION
**Pull request by wseltzer**
remove an extraneous "both" to make the language re Essential Claims make sense

### CODE REVIEW

**Comment by dwsinger** [comment]
It's not extraneous. It's a both-and construction (both A and B). And it's important. We would like a grant for BOTH
* your Essential Claims in your own contribution (even if they were essential in the draft already)
AND
* things that become your Essential Claims as a result of incorporating your contribution (this covers things like combination patents).

**Comment by wseltzer** [comment]
Yes, but "both" is misplaced such that the sentence is un-parseable as written.

**Comment by dwsinger** [comment]
Ah, actually it's "those" that is extraneous

Such commitment should cover, at a minimum, all the contributor’s Essential Claims both in the contribution, and those that become the contributor's Essential Claims as a result of incorporating the contribution into the draft that existed at the time of the contribution

should be

Such commitment should cover, at a minimum, all the contributor’s 
Essential Claims both 
in the contribution, and 
that become the contributor's Essential Claims as a result of incorporating the contribution into the draft that existed at the time of the contribution

**Comment by wseltzer** [comment]
ok, PR updated per @dwsinger's suggestion

**Pull request merged**
