### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by chaals**
Ensure AC review *does* start (at PR)
Update changelog

### CODE REVIEW

**Comment by LJWatson** [comment]
I still do not understand why we want to open the ballot at PR? If the intent of the original change was to enable early feedback by opening the ballot at CR and running it through PR, reverting to opening the ballot at PR seems like a step back.

If we open the ballot at CR and run it for a limited period of time (perhaps 4 weeks), the spec should be stable enough for the AC to make a reasoned decision about its readiness to progress. If there are concerns, then it enables the early feedback the original change sought to enable. 

Feedback, especially concern about readiness to progress,  without the formality of a ballot, seems unlikely to have much impact.

**Comment by dwsinger** [comment]
We have to have a formal AC ballot at some point as to whether the spec. should be published as a Rec. We can't do that at CR because there are questions of implementability, features at risk, and so on. So, we notify the AC at CR (so they can raise any general objections) and then  do the formal ballot at PR. Yes, it should be a question of the AC confirming that i's are dotted, t's crossed, and all is hunky-dory, but we have to ask at some point.

**Comment by LJWatson** [comment]
Thanks @dwsinger. Understood. As you were :)

**Comment by chaals** [comment]
I'm assuming @wseltzer will merge this.

**Comment by chaals** [comment]
Oh. This has been overtaken by a patch from Wendy.

**Pull request closed without merging**
