### PR TITLE
Update note per #172

### PR DESCRIPTION
**Pull request by wseltzer**

### CODE REVIEW

**Comment by dwsinger** [comment]
Hm. I think we need to say something. "Candidate recommendations are expected to be good enough that implementation and experience can happen"?

**Comment by nigelmegitt** [comment]
@dwsinger that's proxy text for the bigger question of expectation that it can be advanced, according to whatever criteria advancement requires. Hence my proposal at https://github.com/w3c/w3process/issues/172#issue-303833491 :

> Candidate Recommendations are expected to be advanced to Recommendation. 

Probably better not to try to mix in advancement criteria here, since that creates an editing dependency should those advancement criteria ever change.

**Comment by frivoal** [comment]
@chaals can you clarify which version looks good to you? the original PR from @wseltzer , or the proposed variant by @nigelmegitt or @dwsinger ?

**Comment by dwsinger** [comment]
see conversation in #172. Some unease about going this way...

**Comment by nrooney** [comment]
It may be better to state in 6.4 "CR should be acceptable as a Rec". Comments?

**Comment by wseltzer** [comment]
Close per Sept 12 meeting

**Comment by dwsinger** [comment]
Looks like a more complex pull is needed, see #172. Closing and waiting for a more comprehensive fix.

**Pull request closed without merging**
