### PR TITLE
Remove references to the Hosts, replace with BoD

### PR DESCRIPTION
**Pull request by frivoal**
***
<a href="https://pr-preview.s3.amazonaws.com/frivoal/w3process/pull/658.html" title="Last updated on Oct 27, 2022, 3:09 PM UTC (0f242f9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/w3process/658/59d34e5...frivoal:0f242f9.html" title="Last updated on Oct 27, 2022, 3:09 PM UTC (0f242f9)">Diff</a>

### CODE REVIEW

**Review by wseltzer — APPROVED** [review]

**Comment by dwsinger** [comment]
Yes, I think it may be time to disentangle formal contracts that legally bind the corporation, from memoranda of understanding that record a mutual understanding and intent.

**Comment by z3r086** [comment]
> 
> 
> 
> 
> ***
> <a href="https://pr-preview.s3.amazonaws.com/frivoal/w3process/pull/658.html" title="Last updated on Oct 27, 2022, 3:09 PM UTC (0f242f9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/w3process/658/59d34e5...frivoal:0f242f9.html" title="Last updated on Oct 27, 2022, 3:09 PM UTC (0f242f9)">Diff</a>

**Comment by mnot** [comment]
> Oversight over the Team, budgeting, and other business decisions is provided by the  W3C Board of Directors , and not subject to the [Process](https://www.w3.org/TR/appmanifest/#dfn-processing-a-manifest).

This can be read to say that the Team is not subject to the Process -- that may not be intended, but we should avoid that impression.

Also, the Process link is wrong.

**Comment by frivoal** [comment]
> Also, the Process link is wrong.

Oops, fixed now, thanks.

> This can be read to say that the Team is not subject to the Process

It's the way Team oversight works (through the Board) which isn't subject to the Process. Grammatically I think that's unambiguous, but if it gives the wrong impression, maybe we should switch to something like this?

> Oversight over the Team, budgeting, and other business decisions is provided by the W3C Board of Directors, rather than managed directly by the Process.

**Comment by mnot** [comment]
That's much better, thanks.

**Comment by frivoal** [comment]
@mnot Treated this as an editorial tweak, and as such applied editorial discretion to fold it in directly.

**Pull request merged**
