### PR TITLE
Editorial tweak in Superseded Recommendation note

### PR DESCRIPTION
**Pull request by tantek**
use "previous" instead of "old" to be more specific, and fix typo: s/or a by a/or by a

### CODE REVIEW

**Comment by frivoal** [comment]
This is a duplicate of https://github.com/w3c/w3process/pull/444

**Comment by tantek** [comment]
Not a duplicate, but same edits to a different branch (main vs 2020 maintenance).

**Comment by frivoal** [comment]
Ah, right, I realized that later, but since I merge the maintenance branch into the main branch anyway, only needed one of the two.

**Comment by tantek** [comment]
Good to know! Thanks and that makes it easier for contributors. Appreciated.

**Pull request closed without merging**
