### PR TITLE
Update #last-call to #candidate-rec links

### PR DESCRIPTION
**Pull request by nrooney**
#171

### CODE REVIEW

**Comment by dwsinger** [comment]
Yes, I think that this is a bad idea, as it break external links (if any)...

**Comment by chaals** [comment]
I'm pretty sure the patent policy still explicitly links to that fragment. Which would be a painful thing to break.

**Comment by nrooney** [comment]
Note to self - add span tag for external ref <span id="last-call"></span>.

**Comment by jeffjaffe** [comment]
@chaals Does this proposed fix when properly done (per Florian) address your concern?

**Comment by chaals** [comment]
@jeffjaffe The concern is that we dont break any link from elsewhere that points to a location within the document using a previously available fragment identifier. Florian describes a couple of ways to do that (there are plenty).

**Comment by frivoal** [comment]
Ok, I've redone that fix, correctly this time. Re-review welcome.

**Comment by frivoal** [comment]
@dwsinger can you have a look, and remove your disapproving review if you agree it is fixed?

**Pull request merged**
